### ISSUE TITLE
footer beutify

### ISSUE THREAD

**Issue by unovajnv** [ankitmalakar7/Hacktoberfest2022#85]

**Comment by unovajnv** [comment]
i can make your footer more beutiful , can you assign it to me please

**Comment by unovajnv** [comment]
make footer more atractive

**Comment by unovajnv** [comment]
can you assign it to me i will make your footer more attractive

**Comment by ankitmalakar7** [comment]
Currently the site don't have any footer at all... Whatever you can work on it, I'm assigning it to you.

**Comment by unovajnv** [comment]
okk okk i am talking about lower part 
and thanku , i am going to make them more beutifull

**Comment by laveshverma007** [comment]
Can you assign it to me

**Comment by ankitmalakar7** [comment]
@laveshverma007 you just do the work and give a PR. I'll definitely look into it.
